name: Custom Recipe Reader
description: Custom GitHub Action to read recipe.json file
inputs:
  json-file:
    description: 'Path to the JSON file'
    required: true
outputs:
  json:
    description: 'JSON content'
runs:
  using: 'node16'
  main: 'index.js'
